1|Catppuccin-Mocha|~/.config/swww/Catppuccin-Mocha/1330654.png
0|Catppuccin-Latte|~/.config/swww/Catppuccin-Latte/1331312.png
0|Decay-Green|~/.config/swww/Decay-Green/moments_before_desk.png
0|Rose-Pine|~/.config/swww/Rose-Pine/1330313.png
0|Tokyo-Night|~/.config/swww/Tokyo-Night/edger_lucy_neon.jpg
0|Material-Sakura|~/.config/swww/Material-Sakura/material_pastel_4.jpg
0|Graphite-Mono|~/.config/swww/Graphite-Mono/japan_lake.jpg
0|Cyberpunk-Edge|~/.config/swww/Cyberpunk-Edge/david.jpg
0|Frosted-Glass|~/.config/swww/Frosted-Glass/min_forest.jpg
