apiVersion: v1
kind: Service
metadata:
  name: result-svc
  labels:
    name: result-svc
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: result-app
    app: demo-voting-app