apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      name: http-frontend
  template:
    metadata:
      labels:
        name: http-frontend
    spec:
      containers:
        - name: nginx
          image: nginx
