--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sin/.config/wpg/wallpapers/dark_arts_custom.png"

-- Special
background="#01080F"
foreground="#a3d8c1"
cursor="#a3d8c1"

-- Colors
color0="#01080F"
color1="#2B635D"
color2="#346C69"
color3="#47776E"
color4="#229B65"
color5="#528979"
color6="#5F9C89"
color7="#a3d8c1"
color8="#729787"
color9="#2B635D"
color10="#346C69"
color11="#47776E"
color12="#229B65"
color13="#528979"
color14="#5F9C89"
color15="#a3d8c1"
